### ISSUE TITLE
Slanting fixes for diagonals and curves (e.g. D, V)

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#214]
In the slanted masters, when things are slanted automatically, it has bad effects on diagonals and curves.

A short tight curve like those seen in the /O or /S is not bad, but a big sweeping curve on the /D is problematic.

With diagonals, a left slope gets thicker when slanted right, and a right slope gets thinner. For example with the /V the left side gets thicker and the right side gets thinner. This needs to be compensated for. For example, in the V, after slanting, the inner triangle of points can be moved to the left, making the left stroke thinner and the right thicker.

The amounts of compensation needed depends on both the thickness of the strokes, and the original angles. A thicker stroke will be more affected, and if the shift is centered on a 45° angle, that maximizes the effect. So for example, the condensed V designs need less adjustment, post-slant.

Done: /A /D /N /M /Q /Q.alt /R /K  /V /W /X /Y /Z  /k /v /w /x /y /z

Brandon done:
/d.smcp /two /two.dnom /four /four.dnom /six /six.dnom /seven /seven.dnom /nine /nine.dnom /ampersand /ampersand.sc /question /question.sc /questiondown /questiondown.sc
/asterisk /uni2116 (numero) /Oslash /oslash.sc /oslash /Lslash /lslash /slash /backslash /fraction /uni2215 /AE /acutecomb /acutecomb.case /gravecomb /gravecomb.case /tildecomb /tildecomb.case /asciitilde /uni1E9E (cap eszett) /uni1E9E.c2sc /asciicircum /uni0302 /uni0302.case /uni0327 (cedilla) /uni0327.case /uni0306 (breve) /uni0306.case /uni0328 (ogonek) /uni0328.case /uni0309 (hook) /uni0309.case /uni031B (horn) /uni031B.case  /trademark /less /greater /greaterequal /lessequal /multiply /uni27E8 /uni27E9 /m.sc /n.sc /q.sc /r.sc /ae.sc 

Backlog (TO DO):
- /uni20AD (kip currency) /uni20B9 (rupee) /uni20BA (Turkish Lira)
- /m.sc /n.sc /w.sc /x.sc /y.sc /z.sc (still need to do :CtrEtc)
- various Cyrillic unique shapes (? Not sure, maybe Vassil already did these

**Comment by tphinney** [comment]
Did  /k /v /w /x /y /z

**Comment by tphinney** [comment]
Brandon did /D

**Comment by kateliev** [comment]
Cyrillic Diagonals fix: /uni0414 /uni041B /uni0409 /uni042F /uni0434 /uni043B /uni0459 /uni0474 /uni0475

**Comment by tphinney** [comment]
Did /N and /M today after I realized they were missing from the list.

Started yesterday on /a.smcp /k.smcp /v.smcp /w.smcp /x.smcp /y.smcp /z.smcp, still in progress.

**Comment by servantb** [comment]
Checked and edited /uni2116, /Oslash, /oslash.sc, and /oslash

**Comment by servantb** [comment]
On Dec 9, adjusted widths of diagonals in slanted masters for /Lslash /lslash /slash /fraction
Made initial adjustments to /backslash, but it has... issues.

**Comment by servantb** [comment]
Issue #214
Adjusted widths of diagonals in slanted masters for /backslash /lslash.sc /AE /acutecomb /acutecomb.case

**Comment by servantb** [comment]
Adjusted widths of diagonals in slanted masters for /gravecomb /gravecomb.case

**Comment by servantb** [comment]
Adjusted widths of diagonals in slanted masters for /tildecomb /tildecomb.case /asciitilde /uni1E9E (cap eszett) and /uni1E9E.c2sc

**Comment by servantb** [comment]
Adjusted widths of diagonals in slanted masters for /asciicircum /uni0302 /uni0302.case

**Comment by servantb** [comment]
Adjusted widths of diagonals in slanted masters for /uni0327 (cedilla) /uni0327.case

**Comment by servantb** [comment]
Adjusted widths of curves in slanted masters for /uni0306 (breve) /uni0306.case /uni0328 (ogonek) /uni0328.case /uni0309 (hook) /uni0309.case /uni031B (horn) /uni031B.case  /trademark

**Comment by servantb** [comment]
Adjusted widths of diagonals in slanted masters for /less /greater /greaterequal /lessequal /multiply /uni27E8 /uni27E9 /m.sc /n.sc /q.sc /r.sc /ae.sc

**Comment by tphinney** [comment]
I have reviewed the thread, and I think the initial message at the top, at the bottom of it, has been repeatedly edited to track fixes. I have just edited it slightly again. I believe this is what remains:

- /uni20AD (kip currency) /uni20B9 (rupee) /uni20BA (Turkish Lira)
- PARTLY done /a.sc /k.sc /v.sc /w.sc /x.sc /y.sc /z.sc (still need to do :CtrEtc)
- various Cyrillic unique shapes (? Not sure, maybe @kateliev already did these)

**Comment by kateliev** [comment]
@tphinney is this still relevant?

**Comment by tphinney** [comment]
Reviewed; Good enough
