### ISSUE TITLE
alternate acute shape for Vietnamese circumflex + acute diacritic combo?

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#224]
Consider using alternate acute (for both regular and cap versions) that trims the bottom left corner and/or is steeper, so as to fit better without sticking out so far to the right. Affects diacritic combinations with a, e, o. (cap, lowercase, small cap).

**Comment by kateliev** [comment]
Note to @kateliev (self):
/circumflexcomb_acutecomb/circumflexcomb_acutecomb.case/circumflexcomb_gravecomb/circumflexcomb_gravecomb.case

![image](https://github.com/user-attachments/assets/90953a39-0e41-4682-a5c3-440786b02d20)

**Comment by kateliev** [comment]
@tphinney these have been reworked
- Redesigned accents: /circumflexcomb_acutecomb/circumflexcomb_acutecomb.case/circumflexcomb_gravecomb/circumflexcomb_gravecomb.case/brevecomb_gravecomb/brevecomb_gravecomb.case/brevecomb_acutecomb/brevecomb_acutecomb.case
- Reworked recipes + fixed anchor non being compatible across masters: /uni1EB0/uni1EA4/uni1EBE/uni1ED0/uni1EA5/uni1EBF/uni1ED1/uni1EA5.sc/uni1EA7.sc/uni1EBF.sc/uni1EC1.sc/uni1ED1.sc/uni1ED3.sc/uni1EA7.slnt

Some proofs follow...

**Original:**
![image](https://github.com/user-attachments/assets/d45398db-5c1c-452d-b78a-2aba8e744d62)
![image](https://github.com/user-attachments/assets/9b375e29-05f7-4eaa-82c6-ed27116ce25f)

**Redesigned:**
![image](https://github.com/user-attachments/assets/a4abb6c0-8e7a-4468-b01c-40a12b1be739)
![image](https://github.com/user-attachments/assets/99c3860a-4187-47d7-825a-9fce50c94eca)
