### ISSUE TITLE
In slanted masters, double quotes and similar have bad "internal spacing" between components

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#229]
A problem occurs in glyphs that meet ALL the following criteria:
- in a :SEtc (slanted) master
- constructed using Glyph Construction Syntax from other glyphs
- constructed from two (or more) components
- components are shifted vertically from their sources

In such cases, the distance between the components is incorrect. It closes up more, the more they are shifted from the source glyph position as part of the GCS formula.

I suspect that the horizontal offset is equal to the tangent of the italic angle times the vertical shift. The first component might be shifted correctly, and the second not, closing the gap between them by this amount. If so, I believe this is a FontLab 7 bug, and have reported it—their issue 4787.

**Comment by kateliev** [comment]
@tphinney could you clarify the issue. I can confirm that there were some glyphs with improper anchor positions that had similar behavior, but without specific string of affected characters i find i very hard to understand the problem...

**Comment by tphinney** [comment]
Darn, I wrote a VERY thorough description, except… I did not give any examples of specific glyphs that exhibit the problem. The linked bug about the double "99" quote marks (/quotedblright) are one example, here: https://github.com/tphinney/science-gothic/issues/275
The double "66" quote marks were unaffected because there is no vertical shift involved.

Looking at the current font:
- /quotedblright is fine (?!)
- uni030B.case (cap combining hungarumlaut) shows the problem
- uni0308.case (cap combining dieresis) does NOT show the problem — but it was decomposed or somehow does not use glyph construction syntax! (Probably to avoid the problem)
- /uni2033 & /uni20BA suffer from a similar spacing inconsistency between upright and slanted masters, despite not having a vertical shift in components?

**Comment by kateliev** [comment]
@tphinney it seems that FL exhibiting some kind of problematic behavior when it comes to auto recipes and slant. I presume it is miscalculation of the transformation data. I have deactivated the auto recipe for each of the affected glyphs, but left them composite. Then I transferred transformation data from non-slanted layers to their slanted counterparts fixing the above discussed problems... 

That has mainly affected all quote-based glyphs (ps: they were having a lot of other bugs that needed addressing), but regretfully (or not) i cannot seem to find any problems with the other discussed glyphs/marks.

 Could you please verify the current fixes and investigate if the other discussed entities still exhibit the above behavior.

**Comment by kateliev** [comment]
Seems fixed long ago :)
