### ISSUE TITLE
Tilde tags: `Q.sc.alt` should have tag `Q.sc~wd<250&wt>350`

### ISSUE THREAD

**Issue by twardoch** [googlefonts/science-gothic#267]
Tilde tags: `Q.sc.alt` should have tag `Q.sc~wd<250&wt>350`. Right now `Q.sc.alt` has `~wd<250&wt>350` so FontLab thinks its source is `Q` (we may change it in future but now it’s so). Same for `uni051B.alt.sc`, should have tilde tag `uni051B.alt~wd<250&wt>350`. Similar for `~wd<490&wt>700`, `~wd<90`, `~wt>800`.

**Comment by tphinney** [comment]
Thanks, will fix.

**Comment by tphinney** [comment]
At some point we had actually dropped q.sc.alt, but I have recreated it, with the correct tag

**Comment by tphinney** [comment]
Oh shoot. It was there, it was just called q.alt.sc
Anyway, fixed the tags on both glyphs

**Comment by tphinney** [comment]
Actually, just a few glitches in Adam's code, although the general principles are sound. Corrected:

Tilde tags: q.alt.sc should have tag q.sc~wd<250&wt>350. Right now q.alt.sc has ~wd<250&wt>350 so FontLab thinks its source is Q (we may change it in future but now it’s so). Same for uni051B.alt.sc, should have tilde tag uni051B.sc~wd<250&wt>350. Similar for ~wd<490&wt>700, ~wd<90, ~wt>800

**Comment by tphinney** [comment]
@twardoch we are having some difficulty with this revised code working in our current build process, which involves exporting UFOs and compiling with Fontmake. Fontmake chokes on it, and removing the code allows the build to work. (@kateliev is that an accurate summary?)

**Comment by kateliev** [comment]
@tphinney isn't this issue #300? If so this is now fixed using other means?
