### ISSUE TITLE
Need requirements.txt

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#283]
Need a file like this at the root level of the repository:
https://github.com/googlefonts/googlefonts-project-template/blob/main/requirements.txt

**Comment by kateliev** [comment]
@tphinney added the necessary file based on our project requirements... 

The file I just pushed is in it's "classic" (txt) form containing all the tools+versions for building the font

```
fontbakery>=0.12.6
fontmake>=3.9.0
gftools[qa]>=0.9.58
sh>=2.0.6
statmake>=0.6.0
```

BUT your link is pointing to a `requirements.txt` file that is supposedly auto-updated (and supported) by a whole build/test chain, that is given as part of a whole [google-fonts-new-submittion-template](https://github.com/googlefonts/googlefonts-project-template/tree/main). This is not bad, just rises the following a question:  Should we not use the provided template and restructure our whole project, or keep it as it is now.  Their `requirements.txt` is actually pointing to a `requirements.in` file that is used by their  `make build ` process and is generated by `make update` command. All utilizing `make` in conjunction with the respected [ makefile](https://github.com/googlefonts/googlefonts-project-template/blob/ca4b21bee0745406b28c1a647d02802634e03a1a/Makefile).

**Comment by tphinney** [comment]
I think the rest of that is covered in #281; see discussion there.
