### ISSUE TITLE
Use gftools-qa instead of just Fontbakery?

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#284]
It is a wrapper around [Fontbakery](https://github.com/googlefonts/fontbakery) and various other proofing scripts

**Comment by kateliev** [comment]
In my opinion totally not worth it. This seems to be a wrapper for a bunch of tools, most not usable to us. Also the fontbakery tests that the thing runs are no different than the ones we are running, but the output is an .md not .html and placed in odd folders. Not really usable compared to our...
`fontbakery check-googlefonts *.ttf --html "sg-build-report.html" --full-lists`

**Comment by tphinney** [comment]
OK, fair enough
