### ISSUE TITLE
Add .loclBGR to existing Cyrillic set

### ISSUE THREAD

**Issue by kateliev** [googlefonts/science-gothic#288]
As discussed in private chat, now it is a good time to add .loclBGR to existing Cyrillic set.

**Comment by tphinney** [comment]
So, it seems the Bulgarian Cyrillic alternates are all designed and wired up, but @kateliev needs to double-check the kerning.

**Comment by kateliev** [comment]
@tphinney i believe this is mostly done. If some kerning issues arise will deal with it as they come. So far i do not see a reason to keep this one open - will close it on our next build...
