### ISSUE TITLE
Regenerate (or delete) non-variable instance fonts because of font weight issues

### ISSUE THREAD

**Issue by JNord03** [googlefonts/science-gothic#301]
The 'w' glyph in both upper and lower case appears to have a higher weight (Medium) in the Regular font than the others. The same applies to numbers 2, 4, 7, 8, the question and exclamation marks and several more with diacritics.
In the Medium font, 'w' looks like a single 'v'.
In the Black font, 'w' appears lighter in color than the rest of the glyphs.
<img width="707" alt="1" src="https://github.com/googlefonts/science-gothic/assets/51972670/0db996e9-5caa-47b5-ac9e-062dc18761a7">

**Comment by tphinney** [comment]
That is interesting. Looks like Windows has some problem with the font that I am not seeing on macOS, nor in Adobe apps.

@kateliev you are on Windows, can you take a look at this?

**Comment by kateliev** [comment]
@tphinney looks like a hinting issue of some sort... will check it out

**Comment by kateliev** [comment]
@tphinney funny enough it is not... actually it is the font itself! But the problem does not reside in the source, it is just the instance generated?

fonts/static/Instances/ScienceGothic-Regular.ttf
![image](https://github.com/googlefonts/science-gothic/assets/10247582/07b55f47-49bf-458b-ae75-a34212135d72)

Actually it seems that ALL of the instances exhibit the very same problem. They seem to be generated from source where `/.notdef/two/four/seven/eight/W/exclam/question/w` were incompatible. But in the current source they are perfectly fine! Which leads me to conclude that there was some export issue perhaps, back then when these were generated?

... and looking at all the TTF rises the following question - all of these fonts that reside in `fonts/static/` are with 177 glyphs strong... but the source is 1234 glyphs. Are these subsets and why?

**Comment by tphinney** [comment]
Oh! It is one of the old instance fonts! Yeah, those are ancient, haven't regenerated them in aeons. I suspect there was a problem in the variable source at the time, but fixed long ago.

**Comment by Elendil03** [comment]
Yes, the problem only occurs in the instances. I downloaded them because I was unable to access any weight other than Light using LibreOffice. The software supports some variable fonts, but apparently not all of them.

**Comment by tphinney** [comment]
Had them VERY EARLY in development. Need to either update them, or delete them, because they are way out of sync with the current variable fonts (with many more bugs).
