### ISSUE TITLE
Add African Pri glyph coverage

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#302]
(UPDATE: Still a moving target when this was written, check for latest data!)

There are about 32 glyphs defined for this. About 15 are already in the current builds of Science Gothic.

Then there are about 8 that need composite glyphs defined (+4 for small caps)

And about 8 (12 including small caps) that need custom new glyphs made, because they are letters with hooks, which are attached rather than floating.

https://github.com/googlefonts/glyphsets/pull/137

https://docs.google.com/spreadsheets/d/10MQCuYIGBDPqYFr1WEYWvu9Tshk5ASsr25NGVcJksYs/edit#gid=0

**Comment by chrissimpkins** [comment]
See the latest updates to the glyph set based on feedback from Neil and Denis.  https://github.com/googlefonts/glyphsets/pull/137/commits/772fe9c07aab90108d70b2907657975a562b8aff

**Comment by tphinney** [comment]
@chrissimpkins hmmm. Funny that it has "0x1e63 LATIN SMALL LETTER S WITH DOT BELOW" but not the matching capital letter. I am going to assume that is an error until/unless somebody tells me differently.

**Comment by kateliev** [comment]
These are now done! 

BUT discussing #309 it just came to me! Currently we are using uniXXXX font naming standard through the typeface, but for the newly generated African glyphs i used friendly names (bit mislead by the google glyphset docs). 

![image](https://github.com/googlefonts/science-gothic/assets/10247582/9f2ba6cc-7d2b-4e52-87bf-2892d97d0d6b)

What shall we do about it:
a) keep it as it is;
b) change it to uniXXXX;

**Comment by tphinney** [comment]
Aha. Yeah, so... honestly the cases where glyph names even MATTER are super corner cases. Mostly for PDF generated from a print stream without a separate font available, AND the font is CFF. I am making some inquiries about this, see how much it matters or Google cares about it, in OT-TTF.

**Comment by tphinney** [comment]
Apparently FontBakery does care. Not sure if it is a WARN or a FAIL. However, I see no warning on this at all from Fontbakery on a font exported directly from FontLab 8.3.

Let’s do a Fontmake based build and also make sure we have the latest Fontbakery, and see what we get.

**Comment by tphinney** [comment]
Well, I did check with the latest Fontbakery and it seems not to object. I wonder if this might be because the TTF export is dropping glyph names? But in any case we seem to be OK.
