### ISSUE TITLE
check spacing of ohorn and uhorn

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#305]
As mentioned in passing in another issue, it looks like ohorn (U+01A1) and uhorn (U+01B0) have inherited the spacing of their base letters without the hook. This is a problem.

**Comment by kateliev** [comment]
@tphinney could you be more specific as i cannot find the glyphs in question. Could you specify unicode value or a glyph name we actually use in the font.

**Comment by tphinney** [comment]
Oops, sorry about that. Fixed the info, should be clear now.  :)
You’ll see that the advance width is inherited, leading to problems for the right sidebearing.

**Comment by kateliev** [comment]
Fixed! Will be in our next build!
