### ISSUE TITLE
Slant alternates interfering with smallcaps

### ISSUE THREAD

**Issue by kateliev** [googlefonts/science-gothic#307]
@tphinney just noticed that the slant alternates are not playing nice with SMCP feature. Look at the` /a`
![image](https://github.com/googlefonts/science-gothic/assets/10247582/5ae1e89d-0918-4ae0-9bdd-4a58b0173bbd)

I presume this is fixable the same way as #300?

**Comment by tphinney** [comment]
Yes, I can’s see why that approach would not work here.  :)

**Comment by kateliev** [comment]
Fixed using FEA code for: "a.slnt","f.slnt","agrave.slnt","aacute.slnt","acircumflex.slnt","atilde.slnt","adieresis.slnt","aring.slnt","abreve.slnt","amacron.slnt","aringacute.slnt","uni0201.slnt","uni0203.slnt","uni1EA1.slnt","uni1EA7.slnt","uni1EAB.slnt","uni1EB7.slnt","uni1EB1.slnt","uni1EA5.slnt","uni1EA9.slnt","uni1EAF.slnt","uni1EB3.slnt","uni1EB5.slnt","uni1EA3.slnt","uni1EAD.slnt","uni0430.slnt","uni04D1.slnt","uni04D3.slnt","aogonek.slnt";

Also added missing: "uni1EA1.sc","uni1EA3.sc";
