### ISSUE TITLE
combining dieresis is misnamed in uni1E85.sc recipe?

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#309]
I would have fixed this myself, but I am torn on which fix is better, so… let me explain.

I see this for every master of uni1E85.sc (small cap w with dieresis):
> Warning: generated '[uni1E85.sc](glyph:uni1E85.sc):Blk Exp Ctr S', ignoring the missing 'dieresiscomb'

The problem is that the "dieresiscomb" is actually named "uni0308" in the font

We do have "acutecomb" and others in the font, pretty sure the "dieresiscomb" name is in AGL, so maybe instead of changing this one recipe, we could/should actually rename the "uni0308" and "uni0308.case" using FontLab internal tools? Would that update the relevant _other_ recipes?

@kateliev feel free to pick the option you think is better here.

**Comment by kateliev** [comment]
Fixed, together with all the recipes and .case alternates. Will be close with our next build
