### ISSUE TITLE
'YOPQ' fvar default does not match registered fallback name

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#319]
## Fontbakery error report

Validate defaults on fvar table match registered fallback names in GFAxisRegistry.
Check ID: com.google.fonts/check/gf_axisregistry/fvar_axis_defaults
Check that axis defaults have a corresponding fallback name registered at the Google Fonts Axis Registry, available at https://github.com/google/fonts/tree/main/axisregistry

This is necessary for the following reasons:

To get ZIP files downloads on Google Fonts to be accurate — otherwise the chosen default font is not generated. The Newsreader family, for instance, has a default value on the 'opsz' axis of 16pt. If 16pt was not a registered fallback position, then the ZIP file would instead include another position as default (such as 14pt).

For the Variable fonts to display the correct location on the specimen page.

For VF with no weight axis to be displayed at all. For instance, Ballet, which has no weight axis, was not appearing in sandbox because default position on 'opsz' axis was 16pt, and it was not yet a registered fallback positon.

🔥 ScienceGothic[YOPQ,slnt,wdth,wght].ttf
🔥 FAIL
The defaul value YOPQ:122.0 is not registered as an axis fallback name on the Google Axis Registry. You should consider suggesting the addition of this value to the registry or adopted one of the existing fallback names for this axis: [name: "Normal" value: 116.0 ] [code: not-registered]

## Commentary

Clearly the notion of Axis Registry defaults plus their usage is at odds with how this axis was defined. The “Normal” value of 116 is font-specific as it represents a per-mill-of-em amount. So if two different families ever have the same value default/normal value, that is pretty much a coincidence. Most likely one could have ten or twenty families and never repeat the same default, just because of how the axis was defined.

I can easily imagine ways to make the axis scale font-independent with a “normal” that will be zero or 100 for all fonts. But that is not what is in the Axis Registry today.

I have no idea what I should actually do in the font, or what should get added to the Registry if two (or more) fonts disagree about what constitutes “Normal”

**Comment by kateliev** [comment]
@tphinney ok shall what shall we do about it:
1. Talk to Google and suggest the above commentary. IMHO it is tally valid, but this is the longest way to fix this;
2. Ignore the FAIL;
3. Make our new Normal 116, as well as Axis end stop as it coincides with our Normal, and forget about it.

**Comment by kateliev** [comment]
I vote for 3) :)

**Comment by kateliev** [comment]
@tphinney deiced to fake solve this by setting the axis user range up to 116 corresponding to our original 122 design maximum. Then by leaving the (Default)=122 produces a new default of 116 of the future STAT table. Then edited our .stylespace accordingly. Thus kept the design in tact and did not scale the axis, in case we change our minds in future. 

For now will close the issue and report back to @yanone. 

Let me know if you are not OK with my decision and i will gladly revert the fix...

**Comment by tphinney** [comment]
I have to admit, I am not 100% comfortable with that approach. But I am not sure I have a better idea, either.  :/
