### ISSUE TITLE
Stylistic Set ss01 needs description string in 'name' table

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#320]
Stylistic sets should provide description text. Programs such as InDesign, TextEdit and Inkscape use that info to display to the users so that they know what a given stylistic set offers.

⚠️ ScienceGothic[YOPQ,slnt,wdth,wght].ttf
⚠️ WARN
The stylistic set ss01 lacks a description string on the 'name' table. [code: missing-description]

**Comment by kateliev** [comment]
Hmm.. I am very much puzzled how one could do this within FontLab? Any ideas?
