### ISSUE TITLE
Recheck for interpolation issues

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#323]
Need to re-run Fontbakery with -F (full lists) to get a proper list of potential issues.

⚠️ ScienceGothic[YOPQ,slnt,wdth,wght].ttf
⚠️ WARN
Interpolation issues were found in the font:

- Contour 2 start point differs in glyph 'uni1EA8' between location YOPQ=122,slnt=0,wdth=50,wght=900 and location YOPQ=122,slnt=0,wdth=200,wght=100

- Contour 2 start point differs in glyph 'uni1EA8' between location YOPQ=122,slnt=0,wdth=200,wght=100 and location YOPQ=122,slnt=0,wdth=200,wght=900

- Contour 2 start point differs in glyph 'uni1EA8' between location YOPQ=122,slnt=-10,wdth=50,wght=900 and location YOPQ=122,slnt=-10,wdth=200,wght=100

- Contour 2 start point differs in glyph 'uni1EA8' between location YOPQ=122,slnt=-10,wdth=200,wght=100 and location YOPQ=122,slnt=-10,wdth=200,wght=900

- Contour 1 start point differs in glyph 'Wacute' between location YOPQ=122,slnt=-10,wdth=50,wght=900 and location YOPQ=122,slnt=-10,wdth=200,wght=100

- Contour 3 start point differs in glyph 'uni01C4' between location YOPQ=122,slnt=0,wdth=200,wght=100 and location YOPQ=122,slnt=0,wdth=200,wght=900

- Contour 3 start point differs in glyph 'uni01C4' between location YOPQ=122,slnt=-10,wdth=200,wght=100 and location YOPQ=122,slnt=-10,wdth=200,wght=900

- Contour 1 start point differs in glyph 'uni1EC0' between location YOPQ=122,slnt=0,wdth=50,wght=900 and location YOPQ=122,slnt=0,wdth=200,wght=100

- Contour 1 start point differs in glyph 'uni1EC0' between location YOPQ=122,slnt=0,wdth=200,wght=100 and location YOPQ=122,slnt=0,wdth=200,wght=900

- Contour 1 start point differs in glyph 'uni1EC0' between location YOPQ=122,slnt=-10,wdth=50,wght=900 and location YOPQ=122,slnt=-10,wdth=200,wght=100

- 245 more.
Use -F or --full-lists to disable shortening of long lists. [code: interpolation-issues]

**Comment by kateliev** [comment]
@tphinney triple checked these. The /uni01C4/uni1EA8/uni1EC0 glyphs in question are auto-glyphs. They look perfectly fine in both VFC and TTF i had examined. In my opinion this is a false positive due to the wild range of design changes across the masters. Cannot find any other explanation...
