### ISSUE TITLE
Ensure soft_dotted characters lose their dot when combined with marks that replace it

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#326]
Ensure soft_dotted characters lose their dot when combined with marks that replace the dot.
Check ID: com.google.fonts/check/soft_dotted
An accent placed on characters with a "soft dot", like i or j, causes the dot to disappear. An explicit dot above can be added where required. See "Diacritics on i and j" in Section 7.1, "Latin" in The Unicode Standard.

Characters with the Soft_Dotted property are listed in https://www.unicode.org/Public/UCD/latest/ucd/PropList.txt

See also: https://googlefonts.github.io/gf-guide/diacritics.html#soft-dotted-glyphs

⚠️ ScienceGothic[YOPQ,slnt,wdth,wght].ttf
⚠️ WARN
The dot of soft dotted characters used in orthographies must disappear in the following strings: i̊ i̋ j̀ j́ j̃ j̄ j̈ j̑ į̀ į́ į̂ į̃ į̄ į̌ і́ ị̀ ị́ ị̂ ị̃ ị̄

The dot of soft dotted characters should disappear in other cases, for example: i̇ ǐ i̒ i̛̇ i̛̊ i̛̋ ǐ̛ i̛̒ i̤̇ i̤̊ i̤̋ ǐ̤ i̤̒ i̦̇ i̦̊ i̦̋ ǐ̦ i̦̒ i̧̇ i̧̊

Your font fully covers the following languages that require the soft-dotted feature: Lithuanian (Latn, 2,357,094 speakers), Ukrainian (Cyrl, 29,273,587 speakers), Igbo (Latn, 27,823,640 speakers), Dutch (Latn, 31,709,104 speakers), Navajo (Latn, 166,319 speakers), Belarusian (Cyrl, 10,064,517 speakers), Ebira (Latn, 2,200,000 speakers).

Your font does not cover the following languages that require the soft-dotted feature: Gulay (Latn, 250,478 speakers), Mango (Latn, 77,000 speakers), Sar (Latn, 500,000 speakers), Ma’di (Latn, 584,000 speakers), Lugbara (Latn, 2,200,000 speakers), Avokaya (Latn, 100,000 speakers), Kom (Latn, 360,685 speakers), Aghem (Latn, 38,843 speakers), Basaa (Latn, 332,940 speakers), Koonzime (Latn, 40,000 speakers), Nateni (Latn, 100,000 speakers), Dan (Latn, 1,099,244 speakers), Ejagham (Latn, 120,000 speakers). [code: soft-dotted]

**Comment by kateliev** [comment]
Test String:  i̊ i̋ j̀ j́ j̃ j̄ j̈ j̑ į̀ į́ į̂ į̃ į̄ į̌ і́ ị̀ ị́ ị̂ ị̃ ị̄ i̇ ǐ i̒ i̛̇ i̛̊ i̛̋ ǐ̛ i̛̒ i̤̇ i̤̊ i̤̋ ǐ̤ i̤̒ i̦̇ i̦̊ i̦̋ ǐ̦ i̦̒ i̧̇ i̧̊

**Comment by kateliev** [comment]
@tphinney this is now done according to [Google standards](https://googlefonts.github.io/gf-guide/diacritics.html#soft-dotted-glyphs). Will be in our next build :)

**Comment by kateliev** [comment]
Done long ago!
