### ISSUE TITLE
fix sidebearings and anchor positions on Oopen / oopen / oopen.sc

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#329]
U+0186 & U+0254
Looks like these were made by rotating the C/c glyphs 180°.

However, that means the sidebearings needed to be swapped, and I don’t think this was done, or maybe only for the Regular? Perhaps it was an operation that was done on the current master instead of “all masters.”

Similarly the anchor positions seem off for ~ the same reason

**Comment by kateliev** [comment]
> Looks like these were made by rotating the C/c glyphs 180°.

Kind of... curious enough the oopen.sc was not slanted on the slanted masters?!

> However, that means the sidebearings needed to be swapped, and I don’t think this was done, or maybe only for the Regular?

Exactly the case. They had proper SB assignment only on Regular layers

> Similarly the anchor positions seem off for ~ the same reason

Not quite... they were OK on the uprights but completely wrong on the slanted layers

All Done now!
