### ISSUE TITLE
Some spacing accents have no advance width

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#335]
All the non-spacing combining accents correctly have zero advance width. Some, but NOT ALL of the spacing accents have widths: there six that have zero width, but should get width. As these are not used in combining marks they should not break anything else. (e.g. "dieresis" should be the spacing legacy accent, while "uni0308" and its cap ".case" version are non-spacing versions)

🔥 FAIL
Width of legacy accent "dieresis" is zero; should be positive.
[code: legacy-accents-width]

🔥 FAIL
Width of legacy accent "cedilla" is zero; should be positive.
[code: legacy-accents-width]

🔥 FAIL
Width of legacy accent "breve" is zero; should be positive.
[code: legacy-accents-width]

🔥 FAIL
Width of legacy accent "dotaccent" is zero; should be positive.
[code: legacy-accents-width]

🔥 FAIL
Width of legacy accent "ring" is zero; should be positive.
[code: legacy-accents-width]

🔥 FAIL
Width of legacy accent "ogonek" is zero; should be positive.
[code: legacy-accents-width]

**Comment by kateliev** [comment]
Done!
