### ISSUE TITLE
Adjust width/sidebearings for three math glyphs

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#337]
This is only a Warn and we could possibly ignore it (or only do it for /multiply)

Check math signs have the same width.
Check ID: <FontBakeryCheck:com.google.fonts/check/math_signs_width>
It is a common practice to have math signs sharing the same width (preferably the same width as tabular figures accross the entire font family).

This probably comes from the will to avoid additional tabular math signs knowing that their design can easily share the same width.

Original proposal: https://github.com/fonttools/fontbakery/issues/3832
⚠️ ScienceGothic[YOPQ,slnt,wdth,wght].ttf
⚠️ WARN
The most common width is 1438 among a set of 11 math glyphs. The following math glyphs have a different width, though:

Width = 1274: multiply

Width = 1218: approxequal, uni223C

[code: width-outliers]

**Comment by kateliev** [comment]
Same as #324

**Comment by kateliev** [comment]
Done. Set the widths of:
/asciitilde/approxequal/uni223C/multiply/uni2052/equal/logicalnot/plus/uni2212/divide/plusminus/less/greater/notequal/lessequal/greaterequal

As calculated in the below attached document:
[Math_Widths_Tabular.xlsx](https://github.com/user-attachments/files/15835681/Math_Widths_Tabular.xlsx)

Set using Python with script that automatically calculates median across layers: 
[scripts/FontLab/sg-toolbox/SG-Metrics-Tabular-Advance.py](https://github.com/googlefonts/science-gothic/blob/6c482a3399bc328ce1ab6bd95e2572bd0d3349f9/scripts/FontLab/sg-toolbox/SG-Metrics-Tabular-Advance.py)
