### ISSUE TITLE
Small cap M has mismatched start point

### ISSUE THREAD

**Issue by unfa** [googlefonts/science-gothic#339]
I've tested the latest Variable version of Science Gothic in Godot Engine 4.2.2 stable.
It appears that the small capital for the letter "M" is very much broken:

![image](https://github.com/googlefonts/science-gothic/assets/491704/e955ea6b-fc00-49e5-a1fd-a394abba3ebb)

Here's Capital and Small Capital intertwined for comparison.

I've also found that YOPQ == 18 gives good result, byut the higher the YOPQ the worse the Small Captial M is.

**Comment by unfa** [comment]
With YOPQ at 18:
![image](https://github.com/googlefonts/science-gothic/assets/491704/eb32aaff-02a3-4eff-86ea-14cfa7c8f9fe)

**Comment by tphinney** [comment]
It looks awful, but it is a trivial thing to fix. There is just a mismatch in start points between the masters.

**Comment by unfa** [comment]
Wow, thank you for this :)

**Comment by tphinney** [comment]
It may be a bit before we regenerate fonts, but at least it is fixed in source.
