### ISSUE TITLE
v1.017 - hhea metrics do not match

### ISSUE THREAD

**Issue by kenmcd** [googlefonts/science-gothic#342]
From: v1.017.(2024-07-29).from.repo.commit
File: ScienceGothic[YOPQ,slnt,wdth,wght].vfc

GF is going to want these to match.

![typo-metrics-vs-hhea-metrics](https://github.com/user-attachments/assets/910497ec-b962-4172-a5a7-0b55ec152865)

**Comment by kateliev** [comment]
@tphinney this is now done for all masters.

**Comment by tphinney** [comment]
Looks good, thanks!
