### ISSUE TITLE
[Audit] FB Report Build 1.08: Ensure the font supports case swapping for all its glyphs.

### ISSUE THREAD

**Issue by kateliev** [googlefonts/science-gothic#343]
@tphinney the following is a bit ridiculous FAIL connected to #341. I would generally ignore it, but still i need your opinion...
<html>
<body>
<html lang="en" style="font-family: -apple-system, sans-serif;"><body style="margin: 0px;"><main style="max-width: 720px; margin: auto; padding-bottom: 3rem;"><p>Ensure that no glyph lacks its corresponding upper or lower counterpart (but only when unicode supports case-mapping).</p><ul style="margin-top: 0px;"><li>Original proposal:<span> </span><a href="https://github.com/googlefonts/fontbakery/issues/3230">https://github.com/googlefonts/fontbakery/issues/3230</a></li></ul><div style="background-color: rgb(238, 238, 136);"></div><details open=""><summary>🔥 ScienceGothic[YOPQ,slnt,wdth,wght].ttf</summary><div><ul style="margin-top: 0px;"><li class="details_item" style="list-style: none; display: flex; align-items: baseline;"><span class="details_indicator" style="flex: 0 0 5em; font-weight: bold; padding-right: 0.5em; text-align: right;">🔥 FAIL</span><span class="details_text" style="flex: 1 0 0%;"><p>The following glyphs lack their case-swapping counterparts:</p>
Glyph present in the font | Missing case-swapping counterpart
-- | --
U+24B9: CIRCLED LATIN CAPITAL LETTER D | U+24D3: CIRCLED LATIN SMALL LETTER D

[code: missing-case-counterparts]</span></li></ul></div></details>

**Comment by tphinney** [comment]
LOL. Yeah we can ignore this.

Mentioned in discussion with GF folks as well. hah!

**Comment by tphinney** [comment]
Actually, turned out they had already fixed this. I was one release behind on Fontbakery....
