### ISSUE TITLE
[Audit] FB Report Build 1.08: Check tabular widths don't have kerning.

### ISSUE THREAD

**Issue by kateliev** [googlefonts/science-gothic#344]
The following did not go away no matter what we tried.

Generating tabular figures and adding them to the corresponding features + more did not resolve the issue. It seems that FB checks if our figures are nearly tabular in width and then starts complaining. In my opinion we should ignore it - @tphinney what is on your mind?

---------------

EXPERIMENTAL CHECK - Since 2024/Jan/30
Check tabular widths don't have kerning.
Check ID: <FontBakeryCheck:com.google.fonts/check/tabular_kerning>
Tabular glyphs should not have kerning, as they are meant to be used in tables.

This check looks for kerning in: - all glyphs in a font in combination with tabular numerals; - tabular symbols in combination with tabular numerals.

"Tabular symbols" is defined as: - for fonts with a "tnum" feature, all "tnum" substitution target glyphs; - for fonts without a "tnum" feature, all glyphs that have the same width as the tabular numerals, but limited to numbers, math and currency symbols.

This check may produce false positives for fonts with no "tnum" feature and with equal-width numerals (and other same-width symbols) that are not intended to be used as tabular numerals.

Original proposal: https://github.com/fonttools/fontbakery/issues/4440
🔥 ScienceGothic[YOPQ,slnt,wdth,wght].ttf
🔥 FAIL
Kerning between one and zero is -50, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and one is 10, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between two and zero is -10, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and two is -35, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between three and zero is -35, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and three is -35, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between six and zero is -5, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and six is -5, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between eight and zero is -20, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and eight is -20, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between parenleft and zero is 15, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and parenright is 15, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between parenleft.case and zero is 15, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and parenright.case is 15, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between bracketleft and zero is 10, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and bracketright is 10, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between bracketleft.case and zero is 10, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and bracketright.case is 10, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between braceleft and zero is 10, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and braceright is 10, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between braceleft.case and zero is 10, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and braceright.case is 10, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between period and zero is -25, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and period is -25, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between ellipsis and zero is -25, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and ellipsis is -25, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between comma and zero is -25, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and comma is -25, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between quotesinglbase and zero is -25, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and quotesinglbase is -25, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between quotedblbase and zero is -25, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and quotedblbase is -25, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and zero is -35, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and zero is -35, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and four is 15, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between seven and zero is 15, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and seven is 10, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between nine and zero is -20, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and nine is -10, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and percent is 5, should be 0

[code: has-tabular-kerning]
🔥 FAIL
Kerning between zero and perthousand is 5, should be 0

[code: has-tabular-kerning]

**Comment by tphinney** [comment]
I agree. The check even warns that it may have false alerts. Which this is.

**Comment by tphinney** [comment]
We needed to update our Fontbakery installs! This warning will go away in the latest version; they made it smarter.  :)
