### ISSUE TITLE
Basic hinting: standard stems

### ISSUE THREAD

**Issue by kateliev** [googlefonts/science-gothic#345]
@tphinney dealing with the font today i happened to notice that the standard stems in the font do not correspond to the true stem widths. Actually it seems they are all copy of the Regular master... and those are not even near the actual stem widths. IMHO we should address that across all masters. What's your take on this?

![image](https://github.com/user-attachments/assets/241e8536-a745-4bb5-89e1-a90376ae9d22)

**Comment by kateliev** [comment]
Done! Will even attempt some kind of hinting next time i build the instances :)

**Comment by tphinney** [comment]
Absolutely not a requirement, though!

AFAIK Google has no interest in us producing or delivering stand-alone non-variable instance-fonts like this. So, kind of cool, but not something to spend much time on.

**Comment by kateliev** [comment]
This has already been done. Just forgot to close the issue :)
