### ISSUE TITLE
Default axis value names need to match Google specs

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#348]
Change names of defaults for axes as follows:

YOPQ: Regular > Normal
slnt: Regular > Default
slnt: Oblique > ? (NOT Default! Not sure we can support Slanted instances among the default instances?)
wdth: Regular > Normal

> Validate STAT particle names and values match the fallback names in GFAxisRegistry.
> Check ID: <FontBakeryCheck:com.google.fonts/check/STAT/gf_axisregistry>
> Check that particle names and values on STAT table match the fallback names in each axis entry at the Google Fonts Axis Registry, available at https://github.com/google/fonts/tree/main/axisregistry
> 
> 
> Original proposal: https://github.com/fonttools/fontbakery/issues/3022
> 🔥 ScienceGothic[YOPQ,slnt,wdth,wght].ttf
> 🔥 FAIL
> On the font variation axis 'YOPQ', the name 'Regular' is not among the expected ones (Normal) according to the Google Fonts Axis Registry.
> 
> [code: invalid-name]
> 🔥 FAIL
> On the font variation axis 'slnt', the name 'Oblique' is not among the expected ones (Default) according to the Google Fonts Axis Registry.
> 
> [code: invalid-name]
> 🔥 FAIL
> On the font variation axis 'slnt', the name 'Regular' is not among the expected ones (Default) according to the Google Fonts Axis Registry.
> 
> [code: invalid-name]
> 🔥 FAIL
> On the font variation axis 'wdth', the name 'Regular' is not among the expected ones (SuperCondensed, UltraCondensed, ExtraCondensed, Condensed, SemiCondensed, Normal, SemiExpanded, Expanded, ExtraExpanded, UltraExpanded) according to the Google Fonts Axis Registry.
> 
> [code: invalid-name]

**Comment by kateliev** [comment]
Changed!.. but `slnt: Oblique > ? (NOT Default! Not sure we can support Slanted instances among the default instances?)` will keep it as it is for now.

**Comment by kateliev** [comment]
Duplicate #357 fixed in c4df5e91ca63e76e9fc55c4785911ac106b84b94
