### ISSUE TITLE
Д д Л л forms

### ISSUE THREAD

**Issue by ravid-dubsteper** [googlefonts/science-gothic#349]
how about to add these forms to the typeface?
![image_2024-09-01_14-45-16](https://github.com/user-attachments/assets/23e9a426-27cb-446e-a2c9-a53da09546fd)
![image_2024-09-01_14-45-16 (2)](https://github.com/user-attachments/assets/2e2134fd-2d1f-4a7c-bf76-573c1bb7af13)
![image_2024-09-01_14-50-02](https://github.com/user-attachments/assets/ddd32877-9323-4f52-98f3-42b9cecfe244)
![image_2024-09-01_14-50-01](https://github.com/user-attachments/assets/e5c28b6a-5a1c-42b3-a703-748b08d08de1)

**Comment by tphinney** [comment]
Definitely a question for @kateliev as the native Cyrillic user on the team!

**Comment by kateliev** [comment]
@ravid-dubsteper thank you for your suggestion! Unfortunately those are very tricky glyphs to design and require a lot of skill to execute properly. Yes they would have been the obvious choice for the Cyrillic set, especially the Russian one, but back then when we designed the Cyrillic for SG I decided to trop the style and focus more on the triangular one. 

Reasons behind my decision:
- Aesthetic: In my opinion looking bit dated (archaic), especially in high contrast masters - thus not that much in par with the idea of Science (Fiction) Gothic. Also way too squarish leading to a way more monotone outlook.
- Pragmatic: Very tricky design, although looking very simple. Some masters will be looking much better than others. Hard to balance (width wise). Might spark a lot of discussion and unnecessary critique. 

...In the light of the above, triangular was a no-brainer solution... and I guess... some 3 years after I am still standing behind my decision.

If you find that we are badly missing those style variants, we could add those as alternates some time in the future... but would need careful consideration.

**Comment by kateliev** [comment]
@zndxcvbn I must admit you were totally right. The triangular form of /У is now permanent. I was thinking keeping the old form as an alternate, but at the end just discarded it.

@ravid-dubsteper the "square" cyrillic forms were a nice suggestion. They are now part of the font and could be accessed either as `OT salt` or `OT ss01`  features. Please see a short example below.

![Image](https://github.com/user-attachments/assets/f35beb73-e164-4409-9a4b-635c5733bc8b)

Thank you both for your suggestions. I believe we are done here :)
