### ISSUE TITLE
What the software used?

### ISSUE THREAD

**Issue by martin-code1** [googlefonts/science-gothic#352]
What's Font maker used? @tphinney

**Comment by tphinney** [comment]
We use FontLab, which these days is version 8.4.

**Comment by martin-code1** [comment]
Ok i used too. I making geometric sans serif call "Weekend Sans". @tphinney

**Comment by tphinney** [comment]
Note that you don’t need to reopen the issue to comment on it!   :)

Science Gothic is somewhat atypical these days, insofar as it was actually commissioned by Google. Also having so many masters makes it a bit hard to work on! But the design space is huge, which is nice for end users.

**Comment by martin-code1** [comment]
Ok. Thanks! :)
