### ISSUE TITLE
Adjust the top of the ascender on the letter "б"

### ISSUE THREAD

**Issue by RazerGuy** [googlefonts/science-gothic#358]
I’ve noticed an issue with the letter "б" in its current design. The top part of the ascender on "б" is positioned below the cap height, which makes it appear smaller compared to other uppercase letters and Cyrillic characters.

I believe this could be improved by raising the letter "б", so that the top of the ascender aligns with the cap height or even extends slightly above it. This adjustment would help "б" look more proportional and consistent in text.

Option 1: The top part of the ascender is aligned exactly with the cap height.
Option 2: The top part of the ascender is slightly above the cap height, and the middle bar now matches the x-height.

Original:
![Image](https://github.com/user-attachments/assets/ea43c2b8-9f12-4643-a426-19bfed62b464)

Option 1:
![Image](https://github.com/user-attachments/assets/df87740c-7a76-4a0d-94d6-ebc2fef1982d)

Option 2:
![Image](https://github.com/user-attachments/assets/4291a96e-baee-4c36-a6c2-378d4622b140)

**Comment by tphinney** [comment]
As far as I understand it, the top of the “be” should be at the ascender height, which in this typeface is slightly above the cap height. In the regular style of Science Gothic, that is about 140 units higher than it is now.

This seems like a relatively easy fix, but I am assigning this to @kateliev as Cyrillic is his native writing system, and hence he is far more aware of subtleties and needs for this character than I am!

**Comment by kateliev** [comment]
@RazerGuy agreed this is no OK. Actually there is already /б with the desired height in the Bulgarian localization. Made it the default one and removed the one that was questionable. Expect the change in in our coming build.
![Image](https://github.com/user-attachments/assets/d902e875-90a0-41b0-a986-4542916b5f07)
